//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chunnel.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Chunnel.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting &apos;{0}&apos;.
        /// </summary>
        public static string Connecting {
            get {
                return ResourceManager.GetString("Connecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection loop error.
        /// </summary>
        public static string ConnectionLoopError {
            get {
                return ResourceManager.GetString("ConnectionLoopError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating connections....
        /// </summary>
        public static string CreatingConnections {
            get {
                return ResourceManager.GetString("CreatingConnections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating connections config.
        /// </summary>
        public static string CreatingConnectionsConfig {
            get {
                return ResourceManager.GetString("CreatingConnectionsConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating connections config failed.
        /// </summary>
        public static string CreatingConnectionsConfigFailed {
            get {
                return ResourceManager.GetString("CreatingConnectionsConfigFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating connections failed.
        /// </summary>
        public static string CreatingConnectionsFailed {
            get {
                return ResourceManager.GetString("CreatingConnectionsFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP address or host name for left connection end point.
        /// </summary>
        public static string HelpTextLeftAddress {
            get {
                return ResourceManager.GetString("HelpTextLeftAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TCP port for left connection end point.
        /// </summary>
        public static string HelpTextLeftPort {
            get {
                return ResourceManager.GetString("HelpTextLeftPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left connection end point type. Possible values: client, server.
        /// </summary>
        public static string HelpTextLeftType {
            get {
                return ResourceManager.GetString("HelpTextLeftType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP address or host name for right connection end point.
        /// </summary>
        public static string HelpTextRightAddress {
            get {
                return ResourceManager.GetString("HelpTextRightAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TCP port for right connection end point.
        /// </summary>
        public static string HelpTextRightPort {
            get {
                return ResourceManager.GetString("HelpTextRightPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right connection end point type. Possible values: client, server.
        /// </summary>
        public static string HelpTextRightType {
            get {
                return ResourceManager.GetString("HelpTextRightType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP address or host name.
        /// </summary>
        public static string IPAddressOrHostName {
            get {
                return ResourceManager.GetString("IPAddressOrHostName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left connection config.
        /// </summary>
        public static string LeftConnectionConfig {
            get {
                return ResourceManager.GetString("LeftConnectionConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listening &apos;{0}&apos;.
        /// </summary>
        public static string Listening {
            get {
                return ResourceManager.GetString("Listening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recieved from connection &apos;{0}&apos; {1} bytes: {2}.
        /// </summary>
        public static string RecievedBytesFromConnection {
            get {
                return ResourceManager.GetString("RecievedBytesFromConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right connection config.
        /// </summary>
        public static string RightConnectionConfig {
            get {
                return ResourceManager.GetString("RightConnectionConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending to connection &apos;{0}&apos; {1} bytes: {2}.
        /// </summary>
        public static string SendingBytesToConnection {
            get {
                return ResourceManager.GetString("SendingBytesToConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting connections and working loop....
        /// </summary>
        public static string StartingConnectionsAndWorkingLoop {
            get {
                return ResourceManager.GetString("StartingConnectionsAndWorkingLoop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; starting work loop for {1} &lt;-&gt; {2}....
        /// </summary>
        public static string StartingWorkLoop {
            get {
                return ResourceManager.GetString("StartingWorkLoop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TCP connection mode.
        /// </summary>
        public static string TcpConnectionMode {
            get {
                return ResourceManager.GetString("TcpConnectionMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TCP port.
        /// </summary>
        public static string TcpPort {
            get {
                return ResourceManager.GetString("TcpPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported connection end point type &apos;{0}&apos;.
        /// </summary>
        public static string UnsupportedEndPointType {
            get {
                return ResourceManager.GetString("UnsupportedEndPointType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail in working loop.
        /// </summary>
        public static string WorkingLoopFail {
            get {
                return ResourceManager.GetString("WorkingLoopFail", resourceCulture);
            }
        }
    }
}
